# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-dashboard-extension}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Gay"]
  s.date = %q{2010-03-05}
  s.description = %q{Dashboard provides a way to see recent activity in Radiant, and allows extension developers to add to the interface with Radiant regions.}
  s.email = %q{jim@saturnflyer.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "HELP.md",
     "HELP_developer.md",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/dashboard_controller.rb",
     "app/helpers/admin/dashboard_helper.rb",
     "app/views/admin/dashboard/index.html.haml",
     "cucumber.yml",
     "dashboard_extension.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/tasks/dashboard_extension_tasks.rake",
     "public/stylesheets/admin/dashboard.css",
     "radiant-dashboard-extension.gemspec",
     "spec/controllers/dashboard_controller_spec.rb",
     "spec/datasets/dashboard_dataset.rb",
     "spec/helpers/dashboard_helper_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/views/admin/dashboard/index_view_spec.rb"
  ]
  s.homepage = %q{http://github.com/saturnflyer/radiant-dashboard-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Dashboard Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/dashboard_controller_spec.rb",
     "spec/datasets/dashboard_dataset.rb",
     "spec/helpers/dashboard_helper_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec_helper.rb",
     "spec/views/admin/dashboard/index_view_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<radiant>, [">= 0"])
    else
      s.add_dependency(%q<radiant>, [">= 0"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0"])
  end
end

